version: '3.10'
networks:
  web-network:
  backend:

volumes:
    data:
    app:


services:
  db:
    hostname: mariadb
    image: mariadb:11.2.2-jammy
    container_name: mariadb
    networks:
      - backend
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: desarrollo
      MYSQL_USER: freddy
      MYSQL_PASSWORD: 1234
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  
   
  docker-php-cli:
    hostname: php-cli
    container_name: php-cli
  # Define el directio donde se contruye la imagen
  # es la ubicacion donde esta el dockerfile
    build:
      context: ./php-cli
     # network: web-network 
    # Hay que asignar un tty, es el parametro "-i", de lo contrrio
    # el contenedor se muere
    tty: true
    # Define el punto(s) de montaje(es) del contenedor,
    # el parametro "-v"
    volumes:
      - ./app:/var/www/html
    # Indica que se conecte a la red denifida en el parametro iniciar del docker-compose networks:
    # Siendo el parametro "--network" en el comando docker
    networks:
      - web-network
  
  docker-php-fpm:
    hostname: php-fpm
    container_name: php-fpm
    build:
      context: ./php-fpm
    tty: true
    volumes:
      - ./app:/var/www/html
    networks:
      - web-network

  docker-nginx:
    hostname: nginx
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"      
    tty: true

    volumes:
      - ./app:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - data:/var/lib/mysql
    networks:
      - web-network
      - backend