# Version de docker-compose que se esta usando
version: '3'

# define the network
networks:
  web-network:

volumes:
  data:
# Iniciar los servicios
services:
  # Definir los nombres de los servicios
  # que corresponde al parametro "--name"
  docker-php-cli:
  # Define el directio donde se contruye la imagen
  # es la ubicacion donde esta el dockerfile
    build:
      context: ./php-cli
     # network: web-network 
    # Hay que asignar un tty, es el parametro "-i", de lo contrrio
    # el contenedor se muere
    tty: true
    # Define el punto(s) de montaje(es) del contenedor,
    # el parametro "-v"
    volumes:
      - ./app:/var/www/html
    # Indica que se conecte a la red denifida en el parametro iniciar del docker-compose networks:
    # Siendo el parametro "--network" en el comando docker
    networks:
      - web-network
  docker-php-fpm:
    build:
      context: ./php-fpm
    tty: true
    volumes:
      - ./app:/var/www/html
    networks:
      - web-network  
  docker-nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"      
    tty: true
  db:
    image: mariadb:11.2.2-jammy
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: desarrollo
      MYSQL_USER: freddy
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./app:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - data:/var/lib/mysql
    networks:
      - web-network